name: Invalidate Cloudfront Distribution
on: 
  push:
    branches:
      - migration

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: '/FeatureFlagsCo.Portal/src/*'
        AWS_REGION: 'cn-north-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}