# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY FeatureFlagsCo.RabbitMQToGrafanaLoki/*.csproj ./FeatureFlagsCo.RabbitMQToGrafanaLoki/
COPY FeatureFlagsCo.RabbitMqModels/*.csproj ./FeatureFlagsCo.RabbitMqModels/
COPY FeatureFlags.APIs/*.csproj ./FeatureFlags.APIs/
COPY FeatureFlagsCo.APIs.Tests/*.csproj ./FeatureFlagsCo.APIs.Tests/
RUN dotnet restore

# copy everything else and build app
COPY FeatureFlagsCo.RabbitMQToGrafanaLoki/. ./FeatureFlagsCo.RabbitMQToGrafanaLoki/
COPY FeatureFlagsCo.RabbitMqModels/. ./FeatureFlagsCo.RabbitMqModels/
COPY FeatureFlags.APIs/. ./FeatureFlags.APIs/
COPY FeatureFlagsCo.APIs.Tests/. ./FeatureFlagsCo.APIs.Tests/
WORKDIR /source/FeatureFlagsCo.RabbitMQToGrafanaLoki
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/runtime:5.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "FeatureFlagsCo.RabbitMQToGrafanaLoki.dll"]





